const SUBSCRIPTIONS_DB = [
  {
    id: 1,
    FechaVenta: '2022-10-25T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Electro Plus',
    PrecioPlan: 899.0,
    TitularApellidoNombre: 'GALLARDO, IRMA NELDA',
    TitularDocumento: '12345678',
    BeneficiarioApellidoNombre: 'GALLARDO, IRMA NELDA',
    BeneficiarioCedula: '12345678',
    IdVenta: '1',
    IdSuscripcion: '9913',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 2,
    FechaVenta: '2022-10-24T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '2',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 3,
    FechaVenta: '2022-10-23T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '3',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 4,
    FechaVenta: '2022-10-22T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '4',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 5,
    FechaVenta: '2022-10-21T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '5',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 6,
    FechaVenta: '2022-10-20T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '6',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 7,
    FechaVenta: '2022-11-19T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '7',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 8,
    FechaVenta: '2022-10-02T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '8',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 9,
    FechaVenta: '2022-11-17T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '9',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 10,
    FechaVenta: '2022-10-16T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '10',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 11,
    FechaVenta: '2022-10-15T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '11',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 12,
    FechaVenta: '2022-10-14T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '12',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 13,
    FechaVenta: '2022-10-13T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '13',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 14,
    FechaVenta: '2022-10-12T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '14',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 15,
    FechaVenta: '2022-10-21T03:00:00.000Z',
    Canal: 'Telefono',
    RazonProveedor: 'Atsapra',
    PlanNombre: 'Vivienda',
    PrecioPlan: 2499.0,
    TitularApellidoNombre: 'GALLARDO, IRMA NELDA',
    TitularDocumento: '12345678',
    BeneficiarioApellidoNombre: 'GALLARDO, JUAN',
    BeneficiarioCedula: '30456781',
    IdVenta: '15',
    IdSuscripcion: '9989',
    idProveedor: 1,
    idStatus: 1,
  },
  {
    id: 16,
    FechaVenta: '2022-10-25T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Medico',
    PrecioPlan: 200.0,
    TitularApellidoNombre: 'SANCHEZ, PEDRO',
    TitularDocumento: '33643563',
    BeneficiarioApellidoNombre: 'SANCHEZ, PEDRO',
    BeneficiarioCedula: '33643563',
    IdVenta: '16',
    IdSuscripcion: '6653',
    idProveedor: 2,
    idStatus: 1,
  },
  {
    id: 17,
    FechaVenta: '2022-10-21T03:00:00.000Z',
    Canal: 'Telefono',
    RazonProveedor: 'Atsapra',
    PlanNombre: 'Vivienda',
    PrecioPlan: 2499.0,
    TitularApellidoNombre: 'GALLARDO, IRMA NELDA',
    TitularDocumento: '12345678',
    BeneficiarioApellidoNombre: 'GALLARDO, JUAN',
    BeneficiarioCedula: '30456781',
    IdVenta: '15',
    IdSuscripcion: '9989',
    idProveedor: 1,
    idStatus: 1,
  },
];

const REJECTED_DB = [
  {
    FechaVenta: '2022-10-25T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Electro Plus',
    PrecioPlan: 899.0,
    TitularApellidoNombre: 'GALLARDO, IRMA NELDA',
    TitularDocumento: '12345678',
    BeneficiarioApellidoNombre: 'GALLARDO, IRMA NELDA',
    BeneficiarioCedula: '12345678',
    IdVenta: '1',
    IdSuscripcion: '9913',
    idProveedor: 2,
    idStatus: 5,
    errors: [
      { code: '33', field: 'DNI', description: 'DNI es de extranjero' },
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
      { code: '99', field: 'Domicilio', description: 'Domicilio no existe' },
    ],
  },
  {
    FechaVenta: '2022-10-24T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '2',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 3,
    errors: [
      { code: '33', field: 'DNI', description: 'DNI es de extranjero' },
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
      { code: '99', field: 'Domicilio', description: 'Domicilio no existe' },
    ],
  },
  {
    FechaVenta: '2022-10-23T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '3',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 3,
    errors: [
      { code: '33', field: 'DNI', description: 'DNI es de extranjero' },
      { code: '99', field: 'Domicilio', description: 'Domicilio no existe' },
    ],
  },
  {
    FechaVenta: '2022-10-22T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '4',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 3,
    errors: [
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
    ],
  },
  {
    FechaVenta: '2022-10-21T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '5',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 5,
    errors: [
      { code: '33', field: 'DNI', description: 'DNI es de extranjero' },
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
      { code: '99', field: 'Domicilio', description: 'Domicilio no existe' },
    ],
  },
  {
    FechaVenta: '2022-10-20T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '6',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 5,
    errors: [
      { code: '33', field: 'DNI', description: 'DNI es de extranjero' },
      { code: '99', field: 'Domicilio', description: 'Domicilio no existe' },
    ],
  },
  {
    FechaVenta: '2022-10-02T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '8',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 5,
    errors: [{ code: '33', field: 'DNI', description: 'DNI es de extranjero' }],
  },
  {
    FechaVenta: '2022-10-17T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '9',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 3,
    errors: [
      { code: '33', field: 'DNI', description: 'DNI es de extranjero' },
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
      { code: '99', field: 'Domicilio', description: 'Domicilio no existe' },
    ],
  },
  {
    FechaVenta: '2022-10-16T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '10',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 3,
    errors: [{ code: '33', field: 'DNI', description: 'DNI es de extranjero' }],
  },
  {
    FechaVenta: '2022-10-15T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '11',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 3,
    errors: [
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
    ],
  },
  {
    FechaVenta: '2022-10-14T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '12',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 5,
    errors: [
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
      { code: '99', field: 'Domicilio', description: 'Domicilio no existe' },
    ],
  },
  {
    FechaVenta: '2022-10-13T03:00:00.000Z',
    Canal: 'Web',
    RazonProveedor: 'GLOBAL ASSIST ARGENTINA S.A',
    PlanNombre: 'Odontologia Unico',
    PrecioPlan: 599.0,
    TitularApellidoNombre: 'RODRIGUEZ, LEANDRO',
    TitularDocumento: '23455678',
    BeneficiarioApellidoNombre: 'RODRIGUEZ, LEANDRO',
    BeneficiarioCedula: '23455678',
    IdVenta: '13',
    IdSuscripcion: '9134',
    idProveedor: 2,
    idStatus: 5,
    errors: [
      { code: '33', field: 'DNI', description: 'DNI es de extranjero' },
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
      { code: '99', field: 'Domicilio', description: 'Domicilio no existe' },
    ],
  },
  {
    FechaVenta: '2022-10-21T03:00:00.000Z',
    Canal: 'Telefono',
    RazonProveedor: 'Atsapra',
    PlanNombre: 'Vivienda',
    PrecioPlan: 2499.0,
    TitularApellidoNombre: 'GALLARDO, IRMA NELDA',
    TitularDocumento: '12345678',
    BeneficiarioApellidoNombre: 'GALLARDO, JUAN',
    BeneficiarioCedula: '30456781',
    IdVenta: '15',
    IdSuscripcion: '9989',
    idProveedor: 1,
    idStatus: 3,
    errors: [
      { code: '33', field: 'DNI', description: 'DNI es de extranjero' },
      {
        code: '45',
        field: 'Fecha de Nacimiento',
        description: 'Fecha de nacimiento erronea',
      },
    ],
  },
];

const NEWS_DB = [
  {
    fechaCarga: '2022-10-25T03:00:00.000Z',
    cantidadRegistros: 10,
    activos: 10,
    rechazados: 1,
    cancelados: 0,
    nombreArchivo: 'mock1',
    prestador: 'Marcelo',
    usuario: 'Juanito',
  },
  {
    fechaCarga: '2022-10-26T03:00:00.000Z',
    cantidadRegistros: 12,
    activos: 5,
    rechazados: 5,
    cancelados: 2,
    nombreArchivo: 'mock2',
    prestador: 'Roberto',
    usuario: 'Pepe',
  },
  {
    id: 3,
    fechaCarga: '2022-10-27T03:00:00.000Z',
    cantidadRegistros: 40,
    activos: 30,
    rechazados: 5,
    cancelados: 5,
    nombreArchivo: 'mock3',
    prestador: 'Adalberto',
    usuario: 'Enrique',
  },
  {
    id: 4,
    fechaCarga: '2022-10-28T03:00:00.000Z',
    cantidadRegistros: 12,
    activos: 2,
    rechazados: 8,
    cancelados: 2,
    nombreArchivo: 'mock4',
    prestador: 'Jeronimo',
    usuario: 'Lautaro',
  },
  {
    fechaCarga: '2022-10-30T03:00:00.000Z',
    cantidadRegistros: 50,
    activos: 49,
    rechazados: 1,
    cancelados: 0,
    nombreArchivo: 'mock5',
    prestador: 'Bautista',
    usuario: 'Nicolas',
  },
  {
    fechaCarga: '2022-10-31T03:00:00.000Z',
    cantidadRegistros: 60,
    activos: 60,
    rechazados: 0,
    cancelados: 0,
    nombreArchivo: 'mock7',
    prestador: 'Omar',
    usuario: 'Estanislao',
  },
];

export const SALES_DB = {
  REPORT: SUBSCRIPTIONS_DB,
  PROCESS: NEWS_DB,
  REJECTED: REJECTED_DB,
};
